#!/bin/bash

echo "       _.---._    /\\"
echo "    ./'       \"--`\\//"
echo "  ./              o \\          .-----."
echo " /./\\  )______   \\__ \\        ( help! )"
echo "./  / /\\ \\   | \\ \\  \\ \\       /`-----'"
echo "   / /  \\ \\  | |\\ \\  \\7--- ooo ooo ooo ooo ooo ooo -"
echo "       wWWWw               wWWWw "
echo " vVVVv (___) wWWWw         (___)  vVVVv "
echo " (___)  ~Y~  (___)  vVVVv   ~Y~   (___) "
echo "  ~Y~   \|    ~Y~   (___)    |/    ~Y~ "
echo "  \|   \ |/   \| /  \~Y~/   \|    \ |/ "
echo " \\|// \\|// \\|/// \\|//  \\|// \\\|/// ""
